#!/usr/bin/env bash
# This script displays a list of currently running processes, showing all processes, for all users, including those which might not have a TTY.
# It displays the processes in a user-oriented format and shows the process hierarchy.

ps -auxf
