#!/usr/bin/env bash
# A script contains Function to handle SIGTERM and SIGQUIT signals,
# Function to handle SIGINT signal, registering signal handlers, writing  PID to file, and loop indefinitely.
cleanup() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit
}

int_handler() {
    echo "Y U no love me?!"
}

trap 'cleanup' SIGTERM SIGQUIT
trap 'int_handler' SIGINT

echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
