#!/usr/bin/env bash
# A script contains Function to handle SIGTERM and SIGQUIT signals,
# Function to handle SIGINT signal, registering signal handlers, writing  PID to file, and loop indefinitely.
cleanup() {
    rm -f /var/run/myscript.pid;
    exit
}

echo $$ > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo 'Y U no love me?!'" SIGINT
    trap "echo 'I hate the kill command'; cleanup" SIGTERM
    trap "echo 'I hate the kill command'; cleanup" SIGQUIT
done
