#!/usr/bin/env bash
# Script to manage a process

# Define the argument passed to the script
argv1=$1
# Define the temporary file to store the PID
tmpfile="/var/run/my_process.pid"

# Function to start the process and create the PID file
start_process() {
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
}

# Function to stop the process and remove the PID file
stop_process() {
    sudo pkill -f "./manage_my_process"
    rm /var/run/my_process.pid
}

# Main function to handle start, stop, and restart actions
case "$argv1" in
    start)
        echo "manage_my_process started"
        start_process
        ;;
    stop)
        echo "manage_my_process stopped"
        stop_process
        ;;
    restart)
        echo "manage_my_process restarted"
        stop_process
        start_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
