#!/usr/bin/env bash
# This script displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009

# Use ps command to find lines containing the word "bash" and grep for the current user
ps aux | grep bash | grep "$(whoami)"
